### ISSUE TITLE
Ideas for Thaumic Potatoes 2.

### ISSUE THREAD

**Issue by GlitchReaper** [zxc74171/ThaumicPotatoes2#2]
If this isn't the right way to suggest things reply with what is. Twitch seems to think no one can read more than a paragraph these days.

I have some ideas for future content (and some lore to go with them) if you're interested:

Potatarmor = Constructing and armor set from Potato Alloy Ingots has some interesting properties the seem to come from infusing its bearer with the essence of life. Each unit of the armor has an effect of its own and the set unifies to nourish the user. The helmet grants Night Vision. The chestplate grants Strength. The leggings grant Jump Boost. The boots grant Speed. The full set together grants a Saturation effect. These effects seem low level at first. Maybe it's missing something?

Potaintarmor = Of course! Adding a Potainto to each piece was the answer! Now it seems chestplate, leggings, and boots are at double their previous power and additional effects are added. The helmet now grants Water Breathing. The chestplate now grants Invisibility. The leggings now grant Haste 2. The boots now grant Fire Resistance. Wearing it all grants defense above any mundane armor because the full set now protects the wearer with Resistance 2. I look like a walking Potainto now, but as intimidating as that it I'm probably better off that way.

Potaintools = Potatools granted the new Potainto treatment also seem enhanced. They have far better stats than previously and are now unbreakable. Do I need carry any other tools?

The "Seven Deadly Sins of Potatomancy." A lost art within thaumaturgy was once drawing power from the "Seven Deadly Sins" and was often used to make potent Baubles, which is also a lost art. I attempted to research both paths and they blended as well as perfectly Mashed Potatoes! I have created one for each basic Bauble location and two rings. Altogether they are quite the set!
The Crown of Envy allows me to view all the creatures that I envy for supplies. Worn on the head it causes all creatures within a wide radius to begin Glowing for easy discernment. No one evades the eyes of the Potatoes!
The Heart of Pride is worn over the heart as an amulet and definitely fills me with it. It provides a full Health Boost 5 effect and Regeneration 2 to heal wounds faster.
The Mantle of Wrath is worn on the body as a cloak. The combined forms of Potatoes lead to some serious deep-fried justice! Any creature that strikes the wearer takes Thorns damage and is set on fire, Poisoned, and Withered. This is better than armor since the Thorns can never break it.
The Ring of Gluttony provides a bonus while eating to any hunger and food saturation regained. It's also cheaper than a full set of Potatarmor so it may be more convenient, if not as effective.
The Ring of Greed grants the bearer two added levels of luckiness in whatever they do to fulfill their greed. Looting levels while bearing a weapon, Fortune levels while using anything else, and a Luck 2 effect constantly.
The Belt of Lust attracts some weird attention. All animals will follow the wearer and breed whenever they get the opportunity. Maybe because it's partially made from food?
The Lure of Sloth is most extraordinary. Worn as a charm it seems the constantly act like Bone Meal close to the wearer and any material capable of bearing an ore seems to sometimes spontaneously do so. It certainly makes standing between a Potato farm and a Stone generator much more interesting!

Like my Potato-themed ideas? I also have some cross-mod compatibility ideas if certain mods update to 1.12+.

**Comment by zxc74171** [comment]
Damn, these are really good. Most are out of my reach though, I still struggle with the most basic forge functions...
Anyway, the 7 sins theme fits it pretty well, as I want a total of 7 bosses in the "complete" version of Thaumic Potatoes 2, each representing one primal aspect from Thaumcraft(as of now, Jagaimo is Perditio and Ziemniak is Ordo) and one that stands above all(for now, Fry Cook). Each can be assigned a sin and have their exclusive baubles.

Still, sadly, I'm heading off to college next week. so I won't have much time working on my mod afterwards...Until the winter vacation I guess.  Even then I'm not sure if I have enough time for this. I guess I'll try my best, but don't expect a major update in months. I'll keep your suggestions in mind when I start working on the mod again. Thanks!
